### ISSUE TITLE
RuntimeError: expected device cuda:1 but got device cuda:0

### ISSUE THREAD

**Issue by GaoXinJian-USTC** [saberSabersaber/transformer_OCR#2]
我在训练Mj ST两个数据集时，遇到了RuntimeError: expected device cuda:1 but got device cuda:0报错请问该如何修改呢？Original Traceback (most recent call last):
  File "/home/will/anaconda3/envs/transocr/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/will/anaconda3/envs/transocr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/will/transformer/codes/transformer_OCR-main/model.py", line 129, in forward
    prediction = self.Prediction(contextual_feature.contiguous(), text, is_train)
  File "/home/will/anaconda3/envs/transocr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/will/transformer/codes/transformer_OCR-main/modules/transformer_util.py", line 376, in forward
    enc_src = self.encoder(src, src_mask)
  File "/home/will/anaconda3/envs/transocr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/will/transformer/codes/transformer_OCR-main/modules/transformer_util.py", line 49, in forward
    src = self.dropout(((src) * self.scale) + self.pos_embedding(pos))
RuntimeError: expected device cuda:1 but got device cuda:0

**Comment by Lebron-Harden** [comment]
改用CPU训练就行，这个报错应该是说没找到GPU
